name: Deploy

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install dependencies
        uses: pnpm/action-setup@v4
        with:
          version: 8
          run_install: |
            - args: [--frozen-lockfile]

      - name: Build
        run: npm run build
